name: CI

on:
  push:
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install deps
        run: composer install --prefer-dist --no-interaction
      - name: Lint
        run: composer lint
      - name: Typecheck
        run: composer typecheck
      - name: Tests
        run: composer test